// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HandlePlay: typeof import('./src/components/HandlePlay.vue')['default']
    HanziSelector: typeof import('./src/components/HanziSelector.vue')['default']
    'Mdi:sortAscending': typeof import('~icons/mdi/sort-ascending')['default']
    PartCheckbox: typeof import('./src/components/PartCheckbox.vue')['default']
    PartSelector: typeof import('./src/components/PartSelector.vue')['default']
    ResultPanel: typeof import('./src/components/ResultPanel.vue')['default']
    ToneSymbol: typeof import('./src/components/ToneSymbol.vue')['default']
  }
}

export { }
